# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeFood', '0002_auto_20170205_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PrimeFood.Menu'),
        ),
    ]
