# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeFood', '0005_remove_menu_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='first',
            field=models.BooleanField(default=False),
        ),
    ]
